version: "3.7"

services:

    db:
        image: mysql:5.7
        restart: always
        command: --default-authentication-plugin=mysql_native_password
        ports:
            - "3306:3306"
        environment: 
            - MYSQL_ROOT_PASSWORD=6666
            - MYSQL_USER=jayse
            - MYSQL_PASSWORD=1337
            - MYSQL_DATABASE=flask_db
        volumes:
          - db_volume:/var/lib/mysql
        networks:
            - backend
    flask:
        build: ./flask
        container_name: flask_test
        restart: always
        depends_on: 
            - db
        environment: 
            - APP_DB_HOST=db
            - APP_DB_PORT=3306
            - APP_DB_USER=jayse
            - APP_DB_PASSWORD=1337
            - APP_DB_NAME=flask_db
        expose:
            - '8080'
        networks:
            - backend
    nginx:
        build: ./nginx
        container_name: nginx
        restart: always
        ports:
            - "80:80"
        networks:
            - backend

volumes:
    db_volume :
networks:
    backend:
